### ISSUE TITLE
I don't get the idea behind the SVC Patient appearing both in the Bundle AND the Composition, both 1.1. required. What is the rationale behind that duplication? Suggestion to keep the Composition->subject as THE patient, to remove the Bundle->patient and to move the Bundle->provence into the composition.

### ISSUE THREAD

**Issue by litlfred** [WorldHealthOrganization/ddcc#24]
**I don't get the idea behind the SVC Patient appearing both in the Bundle AND the Composition, both 1.1. required. What is the rationale behind that duplication? Suggestion to keep the Composition->subject as THE patient, to remove the Bundle->patient and to move the Bundle->provence into the composition.**

Document: FHIR.WHO.SVC-RC1\SVC Bundle - FHIR v4.0.1
Section: Formal Views of Profile Content
Organization: Dr Kai Heitmann, health innovation hub, MoH Germany
Mail: kai.heitmann@hih-2025.de

**Comment by lukeaduncan** [comment]
I think there is a benefit in keeping it in the Bundle so if you have the "document" then you have all the information you need and it's part of the signed content, even though it's not likely that the Patient would change, you wouldn't have to look it up from somewhere else to get the name and birth date.

**Comment by litlfred** [comment]
Agree that it is not ideal to have the patient information repeated.   Issue is that there are two slightly conflicting use cases that need the patient information in each.    This will be resolved in RC2.

**Comment by lukeaduncan** [comment]
The document specification states that Composition.subject, Composition.author and Composition.section.entry shall be in the document bundle.  I've update the IG to include those. http://hl7.org/fhir/documents.html#content
